{"name": "test_add_member_address_7", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ncase\\test_add_member_address.py:239: AssumptionFailure\n>>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nAssertionError: 断言开发自检字段\nassert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               case\\test_add_member_address.py:239: AssumptionFailure\nE               >>\tpytest.assume(result[\"body\"][\"code\"] != 200, \"断言开发自检字段\")\nE               AssertionError: 断言开发自检字段\nE               assert False\n\nd:\\python\\lib\\site-packages\\six.py:702: FailedAssumption"}, "description": "\n    添加地址,号码不正确的\n    :return:\n    ", "start": 1615079429961, "stop": 1615079429960, "uuid": "dc1516c5-a8cf-4de0-b7d7-7975cffee6bb", "historyId": "f6165e909f3d438901c155d4719187b3", "testCaseId": "b02459d2c6fe37c43130ff147d5ccc89", "fullName": "case.test_add_member_address#test_add_member_address_7", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_add_member_address"}, {"name": "host", "value": "DESKTOP-BE07TO9"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_add_member_address"}]}